Resources:
  EC2CheckPublicIP:
    Type: 'AWS::Config::ConfigRule'
    Properties:
      ConfigRuleName: ec2-instance-no-public-ip
      Scope:
        ComplianceResourceTypes:
          - 'AWS::EC2::Instance'
      Description: "A Config rule that checks whether Amazon Elastic Compute Cloud (Amazon EC2) instances have a public IP association. The rule is NON_COMPLIANT if the publicIp field is present in the Amazon EC2 instance configuration item. This rule applies only to IPv4"
      Source:
        Owner: "AWS"
        SourceIdentifier: "EC2_INSTANCE_NO_PUBLIC_IP"
  EC2Remediation:
    DependsOn: EC2CheckPublicIP
    Type: 'AWS::Config::RemediationConfiguration'
    Properties:
      ConfigRuleName: ec2-instance-no-public-ip
      ResourceType: AWS::EC2::Instance
      TargetId: AWS-ReleaseElasticIP
      TargetType: SSM_DOCUMENT
      TargetVersion: '1'
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - >-
                arn:aws:iam::<account_id>:role/AutomationServiceRole
        AllocationId:
          ResourceValue:
            Value: RESOURCE_ID
      ExecutionControls:
        SsmControls:
          ConcurrentExecutionRatePercentage: 10
          ErrorPercentage: 10
      Automatic: true
      MaximumAutomaticAttempts: 10
      RetryAttemptSeconds: 600
